### ISSUE TITLE
Cassandra Backend

### ISSUE THREAD

**Issue by at15** [xephonhq/xephon-k#11]
Naiveschema + Tags

- [x] cli for creating the schema (though actually not very needed) 7dfc37a83caff17513afee8befd96543bb1285ed
- [ ] current naive schema with tags is WRONG, tags should be in partiton key .... 16b0675a43ad93a20c2c88f63251d96926f7708c
-  gocql can handle map properly
- [ ] but you can't filter using map, cassandra think this is a very expensive operation and you must use allow fitlering
- [x] read 60cccf712676f814bf4ec2249dd848c2c47e579a 
- [x] write 16b0675a43ad93a20c2c88f63251d96926f7708c
- [x] unify the keyspace to avoid sprintf feb07ab108fdfca1f068963652e977b85ca38aef
- [x] split int and double table feb07ab108fdfca1f068963652e977b85ca38aef
- [ ] use buffer like KairosDB did, write large batch into Cassandra, currently just use the batch size of client

**Comment by at15** [comment]
got sigsegv when I want to create schema while cassandra is not fully started 

````
INFO[0000] create schema for cassandra using default setting pkg=k.cmd 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5c1d76]

goroutine 1 [running]:
panic(0x7c1620, 0xc420016110)
	/home/at15/app/go/src/runtime/panic.go:500 +0x1a1
github.com/xephonhq/xephon-k/vendor/github.com/gocql/gocql.(*Session).Close(0x0)
	/home/at15/workspace/src/github.com/xephonhq/xephon-k/vendor/github.com/gocql/gocql/session.go:336 +0x26
github.com/xephonhq/xephon-k/pkg/storage/cassandra.CreateKeyspace(0x9e8a40, 0xc420144160)
	/home/at15/workspace/src/github.com/xephonhq/xephon-k/pkg/storage/cassandra/schema.go:59 +0x132
github.com/xephonhq/xephon-k/pkg/storage/cassandra.CreateSchema()
	/home/at15/workspace/src/github.com/xephonhq/xephon-k/pkg/storage/cassandra/schema.go:31 +0x34
github.com/xephonhq/xephon-k/pkg/cmd.glob..func2(0xa09020, 0xa294f0, 0x0, 0x0)
	/home/at15/workspace/src/github.com/xephonhq/xephon-k/pkg/cmd/schema.go:13 +0xb0
github.com/xephonhq/xephon-k/vendor/github.com/spf13/cobra.(*Command).execute(0xa09020, 0xa294f0, 0x0, 0x0, 0xa09020, 0xa294f0)
	/home/at15/workspace/src/github.com/xephonhq/xephon-k/vendor/github.com/spf13/cobra/command.go:603 +0x439
github.com/xephonhq/xephon-k/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa08e00, 0x0, 0x0, 0x0)
	/home/at15/workspace/src/github.com/xephonhq/xephon-k/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/xephonhq/xephon-k/vendor/github.com/spf13/cobra.(*Command).Execute(0xa08e00, 0x5, 0xc420011e40)
	/home/at15/workspace/src/github.com/xephonhq/xephon-k/vendor/github.com/spf13/cobra/command.go:648 +0x2b
github.com/xephonhq/xephon-k/pkg/cmd.Execute()
	/home/at15/workspace/src/github.com/xephonhq/xephon-k/pkg/cmd/root.go:31 +0x2d
main.main()
	/home/at15/workspace/src/github.com/xephonhq/xephon-k/pkg/bin/xkd/main.go:9 +0x14
````

**Comment by at15** [comment]
so we still need the in memory structure for filtering the tags

**Comment by at15** [comment]
The cassandra backend is running now, and I think we can delay the implementation of tags to tomorrow, better come up with a small xephon-b today (note, in order to store the benchmark result, I need to allow configure the cluster to use, otherwise what is in memory is lost)

**Comment by at15** [comment]
Since we are currently working on the in memory and local disk storage, it's not likely we have time to keep the Cassandra backend working, the best I can do is to implement all the methods required by interface with `panic("xxx is not implemted")`
