### ISSUE TITLE
Bench KairosDB

### ISSUE THREAD

**Issue by at15** [xephonhq/xephon-k#16]
It got similar performance with Xephon-K, though it seems it lose connection to cassandra?

````
	//INFO[0010] basic report finished via context pkg=k.b.reporter
	//INFO[0010] total request 14191 pkg=k.b.reporter
	//INFO[0010] fastest 237171 pkg=k.b.reporter
	//INFO[0010] slowest 349506588 pkg=k.b.reporter
````

**Comment by at15** [comment]
the error message is 

````
 23:50:40.940 [WriteBuffer-data_points-0] ERROR [HThriftClient.java:132] - Could not flush transport (to be expected if the pool is shutting down) in close for client: CassandraClient<kairosdbcassandra:9160-7>
xephonhq-kairosdb-cp | org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)
xephonhq-kairosdb-cp | 	at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:147)
xephonhq-kairosdb-cp | 	at org.apache.thrift.transport.TFramedTransport.flush(TFramedTransport.java:156)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.connection.client.HThriftClient.close(HThriftClient.java:130)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.connection.client.HThriftClient.close(HThriftClient.java:40)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.connection.HConnectionManager.closeClient(HConnectionManager.java:320)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:268)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.model.ExecutingKeyspace.doExecuteOperation(ExecutingKeyspace.java:113)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.model.MutatorImpl.execute(MutatorImpl.java:243)
xephonhq-kairosdb-cp | 	at org.kairosdb.datastore.cassandra.WriteBuffer$WriteDataJob.run(WriteBuffer.java:308)
xephonhq-kairosdb-cp | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
xephonhq-kairosdb-cp | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
xephonhq-kairosdb-cp | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
xephonhq-kairosdb-cp | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
xephonhq-kairosdb-cp | 	at java.lang.Thread.run(Thread.java:745)
xephonhq-kairosdb-cp | Caused by: java.net.SocketException: Broken pipe (Write failed)
xephonhq-kairosdb-cp | 	at java.net.SocketOutputStream.socketWrite0(Native Method)
xephonhq-kairosdb-cp | 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
xephonhq-kairosdb-cp | 	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
xephonhq-kairosdb-cp | 	at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:145)
xephonhq-kairosdb-cp | 	... 13 common frames omitted
xephonhq-kairosdb-cp | 23:50:40.941 [WriteBuffer-data_points-0] ERROR [HConnectionManager.java:418] - MARK HOST AS DOWN TRIGGERED for host kairosdbcassandra(172.18.0.2):9160
xephonhq-kairosdb-cp | 23:50:40.941 [WriteBuffer-data_points-0] ERROR [HConnectionManager.java:422] - Pool state on shutdown: <ConcurrentCassandraClientPoolByHost>:{kairosdbcassandra(172.18.0.2):9160}; IsActive?: true; Active: 1; Blocked: 0; Idle: 15; NumBeforeExhausted: 49
xephonhq-kairosdb-cp | 23:50:40.942 [WriteBuffer-data_points-0] INFO  [ConcurrentHClientPool.java:189] - Shutdown triggered on <ConcurrentCassandraClientPoolByHost>:{kairosdbcassandra(172.18.0.2):9160}
xephonhq-kairosdb-cp | 23:50:40.942 [WriteBuffer-data_points-0] INFO  [ConcurrentHClientPool.java:197] - Shutdown complete on <ConcurrentCassandraClientPoolByHost>:{kairosdbcassandra(172.18.0.2):9160}
xephonhq-kairosdb-cp | 23:50:40.942 [WriteBuffer-data_points-0] INFO  [CassandraHostRetryService.java:68] - Host detected as down was added to retry queue: kairosdbcassandra(172.18.0.2):9160
xephonhq-kairosdb-cp | 23:50:40.943 [WriteBuffer-data_points-0] WARN  [HConnectionManager.java:302] - Could not fullfill request on this host CassandraClient<kairosdbcassandra:9160-7>
xephonhq-kairosdb-cp | 23:50:40.943 [WriteBuffer-data_points-0] WARN  [HConnectionManager.java:303] - Exception: 
xephonhq-kairosdb-cp | me.prettyprint.hector.api.exceptions.HectorTransportException: org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.service.ExceptionsTranslatorImpl.translate(ExceptionsTranslatorImpl.java:39)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:260)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.model.ExecutingKeyspace.doExecuteOperation(ExecutingKeyspace.java:113)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.model.MutatorImpl.execute(MutatorImpl.java:243)
xephonhq-kairosdb-cp | 	at org.kairosdb.datastore.cassandra.WriteBuffer$WriteDataJob.run(WriteBuffer.java:308)
xephonhq-kairosdb-cp | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
xephonhq-kairosdb-cp | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
xephonhq-kairosdb-cp | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
xephonhq-kairosdb-cp | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
xephonhq-kairosdb-cp | 	at java.lang.Thread.run(Thread.java:745)
xephonhq-kairosdb-cp | Caused by: org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
xephonhq-kairosdb-cp | 	at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:147)
xephonhq-kairosdb-cp | 	at org.apache.thrift.transport.TFramedTransport.flush(TFramedTransport.java:157)
xephonhq-kairosdb-cp | 	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:65)
xephonhq-kairosdb-cp | 	at org.apache.cassandra.thrift.Cassandra$Client.send_batch_mutate(Cassandra.java:958)
xephonhq-kairosdb-cp | 	at org.apache.cassandra.thrift.Cassandra$Client.batch_mutate(Cassandra.java:949)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:246)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.model.MutatorImpl$3.execute(MutatorImpl.java:243)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.service.Operation.executeAndSetResult(Operation.java:104)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:253)
xephonhq-kairosdb-cp | 	... 8 common frames omitted
xephonhq-kairosdb-cp | Caused by: java.net.SocketException: Connection reset
xephonhq-kairosdb-cp | 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
xephonhq-kairosdb-cp | 	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
xephonhq-kairosdb-cp | 	at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:145)
xephonhq-kairosdb-cp | 	... 16 common frames omitted
xephonhq-kairosdb-cp | 23:50:40.943 [WriteBuffer-data_points-0] INFO  [HConnectionManager.java:404] - Client CassandraClient<kairosdbcassandra:9160-7> released to inactive or dead pool. Closing.
xephonhq-kairosdb-cp | 23:50:40.944 [WriteBuffer-data_points-0] ERROR [WriteBuffer.java:315] - Error sending data to Cassandra (data_points)
xephonhq-kairosdb-cp | me.prettyprint.hector.api.exceptions.HectorException: All host pools marked down. Retry burden pushed out to client.
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.connection.HConnectionManager.getClientFromLBPolicy(HConnectionManager.java:390)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:244)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.model.ExecutingKeyspace.doExecuteOperation(ExecutingKeyspace.java:113)
xephonhq-kairosdb-cp | 	at me.prettyprint.cassandra.model.MutatorImpl.execute(MutatorImpl.java:243)
xephonhq-kairosdb-cp | 	at org.kairosdb.datastore.cassandra.WriteBuffer$WriteDataJob.run(WriteBuffer.java:308)
xephonhq-kairosdb-cp | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
xephonhq-kairosdb-cp | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
xephonhq-kairosdb-cp | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
xephonhq-kairosdb-cp | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
xephonhq-kairosdb-cp | 	at java.lang.Thread.run(Thread.java:745)
xephonhq-kairosdb-cp | 23:50:40.944 [WriteBuffer-data_points-0] ERROR [WriteBuffer.java:319] - Reducing write buffer size to 375000.  You need to increase your cassandra capacity or change the kairosdb.datastore.cassandra.write_buffer_max_size property.
xephonhq-kairosdb-cp | 23:50:40.962 [Hector.me.prettyprint.cassandra.connection.CassandraHostRetryService-1] INFO  [HConnectionManager.java:109] - Added host kairosdbcassandra(172.18.0.2):9160 to pool
`````

**Comment by at15** [comment]
Close in favor of #60 

KairosDB is what Xephon-K originally modeled after, said thing is, it's becoming a strawman now ...
